---
- name: setup the rules directory
  file: path="{{ csirtg_smrt_rules_path }}" state=directory mode=770 owner="{{ app_user }}" group="{{ app_group }}" recurse=yes

- name: copy csirtg-smrt rules
  command: cp -r "/tmp/bearded-avenger-{{ cif_release }}/rules/default/" "{{ csirtg_smrt_rules_path }}"
  tags: rules

- name: Update rule permissions
  file:
    path: "{{ csirtg_smrt_rules_path }}/default"
    mode: u=rwX,g=rwX,o=
    recurse: yes
    owner: "{{ app_user }}"
    group: "{{ app_group }}"